### ISSUE TITLE
[BUG] - 

### ISSUE THREAD

**Issue by FroztIkon** [invernyx/smartcars-3-public-api#102]
### Describe the bug

PHP Warning:  file_get_contents(../../env.php): Failed to open stream: No such file or directory in /home/uavirtual/domains/vms.uavirtual.org/public_html/cars/0.3.6/handlers/phpvms7/environment.php on line 6
PHP Warning:  Undefined array key 1 in /home/uavirtual/domains/vms.uavirtual.org/public_html/cars/0.3.6/handlers/phpvms7/environment.php on line 9
PHP Warning:  Undefined array key 1 in /home/uavirtual/domains/vms.uavirtual.org/public_html/cars/0.3.6/handlers/phpvms7/environment.php on line 10
PHP Warning:  Undefined array key 1 in /home/uavirtual/domains/vms.uavirtual.org/public_html/cars/0.3.6/handlers/phpvms7/environment.php on line 11
PHP Warning:  Undefined array key 1 in /home/uavirtual/domains/vms.uavirtual.org/public_html/cars/0.3.6/handlers/phpvms7/environment.php on line 12
PHP Warning:  Undefined array key 1 in /home/uavirtual/domains/vms.uavirtual.org/public_html/cars/0.3.6/handlers/phpvms7/environment.php on line 13

### How do you reproduce this bug?

Attempt to make use of SmartCars 3 to login as pilot
API preview call (ie .../api/phpvms7) 

### Expected behavior

Allow SmartCars 3 to login

### API Version

0.3.6

### PHP Version

 8.1.23

### Database & version

MariaDB version 10.6.12

### Webserver version

Apache version 2.4.52 ubuntu 22.04

### Browser

Vivaldi 6.2 & Chrome 117.0.5

### Handler

phpvms7

**Comment by FroztIkon** [comment]
Please close this with an update to:

environment.php

change the call from 
file_get_contents(../../env.php)
to
file_get_contents(../../.env)

**Comment by GenericNerd** [comment]
This call is already made by the API. I highly suggest updating phpVMS 7 and the API.
