### ISSUE TITLE
[BUG] - flight/complete.php calls database incorrectly

### ISSUE THREAD

**Issue by walkerair** [invernyx/smartcars-3-public-api#14]
**Describe the bug**
The database query for the schedule information doesn't appear to function with an =? in the string. This causes the PIREP to not be filed, even though the application says that it was.

**To Reproduce**
1. Fly
2. Click End Flight
3. Check logbook and see no flight

**Expected behavior**
Flight should be submitted to the database.

**Screenshots**
N/A

**System Information (please complete the following information):**
 - OS: Windows 11
 - Community ID: N/A
 - Version: Webscripts 0.2.3
 - Plugins used: N/A

**Additional context**
Line 26 in phpvms5/flights/complete.php
$route = $database->fetch('SELECT code, flightnum, depicao, arricao, route, aircraft FROM ' . dbPrefix . 'schedules WHERE id=?', $bids[0]['routeid']);

Works if changed to:
$route = $database->fetch('SELECT code, flightnum, depicao, arricao, route, aircraft FROM ' . dbPrefix . 'schedules WHERE id=', $bids[0]['routeid']);

**Comment by GenericNerd** [comment]
This is a known fix already fixed in the development version.
