### ISSUE TITLE
[BUG] - Error connecting to script URL - 301 - Redirects Are Not Allowed

### ISSUE THREAD

**Issue by ChrisAHD** [invernyx/smartcars-3-public-api#32]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System Information (please complete the following information):**
 - Version [e.g. 0.3.1]
 - PHP version: [e.g. 8.0.11]
 - Database version: [e.g. 10.5.12-MariaDB]
 - Webserver version: [e.g. Apache/2.4.51 (Win64) OpenSSL/1.1.1l PHP/8.0.11]
 - Browser: [e.g. Chrome 96.0.4664.110]
 - Handler: [e.g. phpvms5]

**Additional context**

**Comment by ChrisAHD** [comment]
Error connecting to script URL - 301 - Redirects Are Not Allowed wht's causing this issue SmartCars 3

**Comment by GenericNerd** [comment]
This is intentional smartCARS Central behaviour and not an API bug. This issue is invalid
