### ISSUE TITLE
[BUG] - News Page Showing First rather than most recent

### ISSUE THREAD

**Issue by CaptainMac2336** [invernyx/smartcars-3-public-api#34]
**Describe the bug**
The home screen for SC3 has a place to display our news feed. Currently, the newsfeed is showing the first ever news "article" we posted on our site rather than the latest.

**To Reproduce**
Open SmartCARS and there it is. 

**Expected behavior**
The display should show our latest news release only. 

**Screenshots**
N/A

**System Information (please complete the following information):**
 - OS: Windows 10
 - Community ID: 
 - Version beta release
 - Plugins used: [chat, flight-breakdown, flight-center, flight-tracking, map-plugin, pilot-center, simbrief]

**Additional context**

**Comment by GenericNerd** [comment]
Transferred to API bug
