### ISSUE TITLE
[FEATURE] - Make return pirepID as string for both phpvms5 & 7

### ISSUE THREAD

**Issue by bgiorgio0506** [invernyx/smartcars-3-public-api#42]
### Describe the bug

pirepID are numbers in phpvms 5 and are either number and string in phpvm7

### How do you reproduce this bug?

Submit a pirep in phpvm7 and you can get a UUID type so string or numbers.

### Expected behavior

Make both phpvms  5 and phpvms 7 send a string

### API Version

0.8.3

### PHP Version

8.0.11

### Database & version

MariaDB

### Webserver version

Apache

### Browser

Chrome

### Handler

phpvms5 & phpvms7

**Comment by GenericNerd** [comment]
It is not what we want to force future API developers to conform to string IDs only. Some, if not most developers will use integer IDs and will not be aware that they will have to send it as a string.
