### ISSUE TITLE
[BUG] - Cancelling an ongoing flight should remove the relevant data from the smartCARS3_OngoingFlights

### ISSUE THREAD

**Issue by Thien42** [invernyx/smartcars-3-public-api#60]
### Describe the bug

When a user cancels a flight, the entries in the `smartCARS3_OngoingFlights` table are still there.
This can lead to a wrong pilot report in case the user decides to fly the same bid at a later time. 

### How do you reproduce this bug?

1. Submit a bid
2. Start a flight with SC3
3. Cancel the flight after starting it
4. There is still data left in the the `smartCARS3_OngoingFlights` table 

### Expected behavior

When a user cancels a flight from SC3, the relevant entries from the `smartCARS3_OngoingFlights` table are removed.
The same thing should happen when a user unbooks the flight, to prevent unnecessary data usage.
We should consider creating a new endpoint `flight/cancel` that would remove that data.

### API Version

0.3.3

### PHP Version

8.0.11

### Database & version

8.0.33

### Webserver version

Apache 2

### Browser

Any

### Handler

Any

**Comment by jordanhavard** [comment]
Big +1 for this

**Comment by GenericNerd** [comment]
Resolved in 0.3.5
