### ISSUE TITLE
[BUG] - phpVMS 7 ACARS Table is not written to in update.php

### ISSUE THREAD

**Issue by BossOfGames** [invernyx/smartcars-3-public-api#76]
### Describe the bug

When smartCARS sends the position reports via the API's update.php file, it appears to not be writing to the `acars` table. When a pilot submits the PIREP, the complete.php fails with a 404 error in checking if the flight exists in the `acars` table.

### How do you reproduce this bug?

N/A

### API Version

development branch

### PHP Version

8.1

### Database & version

MySQL 8

### Webserver version

Nginx

### Browser

N/A

### Handler

phpvms7

### Additional context

![image](https://github.com/invernyx/smartcars-3-public-api/assets/2882332/b967650f-03ad-4672-b86b-5ee262786d8b)

![image](https://github.com/invernyx/smartcars-3-public-api/assets/2882332/cbdf3280-5ab9-42ee-9b45-6d8fc13dc5e8)

**Comment by GenericNerd** [comment]
With no instructions on how to reproduce the bug, it is impossible to determine what the issue is. We would also need the message associated with the 404, which you have not provided.
