### ISSUE TITLE
[BUG] - Flight Center - Schedule Flight Times Not Displayed Correctly

### ISSUE THREAD

**Issue by bryan737dfw** [invernyx/smartcars-3-public-api#87]
### Describe the bug

In the search for a flight result list in Flight Center, the flight times (duration) that are displayed are incorrect.

In phpVMS, the flight time is stored as a decimal number representing HH:MM (ie: 06:14 = 6.14).  It looks like SC3 is not treating what is after the decimal as the minutes.  

![image](https://github.com/invernyx/smartcars-3-bugs/assets/74014089/6e78ff72-65e8-4496-ae9c-49305a925200)

For example for a flight time of 06:14, this is stored as 6.14 in phpVMS.  In SC2, the flight time display correctly as 6:14.  However, SC3 displays this as 06h 08m.  It looks like SC3 is multiplying the minutes (what comes after the decimal) by 60.  So, ( .14 * 60) gives 8.4... which seems to be what is displayed by SC3.

### How do you reproduce this bug?

1. Open Flight Center.
2. Click New Bid.
3. Can enter search criteria or not... as long as a list of flights appears.

### Expected behavior

The flight time displayed should match what is on the flight schedule.  The flight times display correctly in SC2.

### Screenshots

SC2:

![image](https://github.com/invernyx/smartcars-3-bugs/assets/74014089/02016d4c-137b-49ae-aff8-92bdfe42b4bc)

SC3:

![image](https://github.com/invernyx/smartcars-3-bugs/assets/74014089/e90a39c2-b4eb-429d-821a-9457452bda1d)

### Operating system

Windows 10 22H2

### Community airline

Noble Air

### smartCARS Version

0.12.0

### Plugins installed

Chat 0.11.0, Flight Center 0.10.1, Flight Tracking 0.12.0, Logbook 0.10.1, Map 0.10.0, SimBrief 0.10.1

**Comment by GenericNerd** [comment]
This has already been fixed in the upcoming version of 0.3.5
